// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwxfGjECB4AmDDZ5Izi7NkYSiIt4CAW_4',
    appId: '1:869504266615:web:37ec13ae9d4297cbfb3172',
    messagingSenderId: '869504266615',
    projectId: 'eduve-bc350',
    authDomain: 'eduve-bc350.firebaseapp.com',
    storageBucket: 'eduve-bc350.firebasestorage.app',
    measurementId: 'G-PL6YYTTRQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUGSEPW7bwZiI1cDrjJu1JjNRo7Vm8qLE',
    appId: '1:869504266615:android:26a05dd58a9c98edfb3172',
    messagingSenderId: '869504266615',
    projectId: 'eduve-bc350',
    storageBucket: 'eduve-bc350.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEJ0DkS9cO9xS0oGWV-XfATlJpWQy6t58',
    appId: '1:869504266615:ios:9e9cdcedf3366b8cfb3172',
    messagingSenderId: '869504266615',
    projectId: 'eduve-bc350',
    storageBucket: 'eduve-bc350.firebasestorage.app',
    androidClientId: '869504266615-19bmfolbt7kolc202joc7oshbv16tvg9.apps.googleusercontent.com',
    iosClientId: '869504266615-4gi2nuaeh83ei0vjltfres5t3r1ent7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

}